export const employeeTypes = {

  /*get employee*/
  SET_GET_EMPLOYEE_LOADING: 'SET_GET_EMPLOYEE_LOADING',
  GET_EMPLOYEE: 'GET_EMPLOYEE',
  SET_GET_EMPLOYEE: 'SET_GET_EMPLOYEE',
  SET_GET_EMPLOYEE_ERROR: 'SET_GET_EMPLOYEE_ERROR',

  /*add employee*/
  SET_ADD_EMPLOYEE_LOADING: 'SET_ADD_EMPLOYEE_LOADING',
  ADD_EMPLOYEE: 'ADD_EMPLOYEE',
  SET_ADD_EMPLOYEE: 'SET_ADD_EMPLOYEE',
  SET_ADD_EMPLOYEE_ERROR: 'SET_ADD_EMPLOYEE_ERROR',

  /*get employee by id*/
  SET_GET_EMPLOYEE_BY_ID_LOADING: 'SET_GET_EMPLOYEE_BY_ID_LOADING',
  GET_EMPLOYEE_BY_ID: 'GET_EMPLOYEE_BY_ID',
  SET_GET_EMPLOYEE_BY_ID: 'SET_GET_EMPLOYEE_BY_ID',
  SET_GET_EMPLOYEE_BY_ID_ERROR: 'SET_GET_EMPLOYEE_BY_ID_ERROR',

  /*update employee*/
  SET_UPDATE_EMPLOYEE_LOADING: 'SET_UPDATE_EMPLOYEE_LOADING',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  SET_UPDATE_EMPLOYEE: 'SET_UPDATE_EMPLOYEE',
  SET_UPDATE_EMPLOYEE_ERROR: 'SET_UPDATE_EMPLOYEE_ERROR',

  /*delete employee*/
  SET_DELETE_EMPLOYEE_LOADING: 'SET_DELETE_EMPLOYEE_LOADING',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  SET_DELETE_EMPLOYEE: 'SET_DELETE_EMPLOYEE',
  SET_DELETE_EMPLOYEE_ERROR: 'SET_DELETE_EMPLOYEE_ERROR',
};